services:
    bondy-service:
        image: leapsight/bondy:develop-otp25
        container_name: bondy
        hostname: bondy
        environment:
            BONDY_ERL_NODENAME: bondy@127.0.0.1
            BONDY_ERL_DISTRIBUTED_COOKIE: bondy
        env_file:
            - .env
        user: "0:1000"
        ports:
            # WS/HTTP
            - "18080:18080"
            # WS/HTTP Admin
            - "18081:18081"
            # TCP
            - "18082:18082"
            # HTTPS
            - "18083:18083"
            # Clustering
            - "18086:18086"
        volumes:
            - ./bondy/etc:/bondy/etc
